/* jenner-check bundle autoexec.
   Mock CDM "indata" library standing in for the site's C:\CDM_folder\.
   indata.tumor_new is a Version-2025 tumor table: it declares every camelCase
   NAACCR field that the repo's %version backward-compatibility macro renames,
   so the macro can run verbatim. Values are synthetic placeholders ('.'); the
   point of this bundle is exercising the macro's variable-rename logic. */
options obs=100;
libname indata '.';

data indata.tumor_new;
    length registryType $1 naaccrRecordVersion $1 tumorRecordNumber $1 addrAtDxState $1 stateAtDxGeocode19708090 $1 stateAtDxGeocode2000 $1 ;
    length stateAtDxGeocode2010 $1 stateAtDxGeocode2020 $1 addrAtDxCountry $1 censusCodSys19708090 $1 censusTrPovertyIndictr $1 maritalStatusAtDx $1 ;
    length race1 $1 race2 $1 race3 $1 race4 $1 race5 $1 spanishHispanicOrigin $1 ;
    length nhiaDerivedHispOrigin $1 ihsLink $1 raceNapiia $1 computedEthnicity $1 computedEthnicitySource $1 sex $1 ;
    length ageAtDiagnosis $1 dateOfBirth $1 birthplaceState $1 birthplaceCountry $1 censusIndCode2010 $1 censusOccCode2010 $1 ;
    length occupationSource $1 industrySource $1 ruca2000 $1 ruca2010 $1 uric2000 $1 uric2010 $1 ;
    length censusTrCert19708090 $1 censusTrCertainty2000 $1 gisCoordinateQuality $1 censusTrCertainty2010 $1 censusTractCertainty2020 $1 sequenceNumberCentral $1 ;
    length dateOfDiagnosis $1 primarySite $1 laterality $1 histologyIcdO2 $1 behaviorIcdO2 $1 grade $1 ;
    length gradePathValue $1 ambiguousTerminologyDx $1 dateConclusiveDx $1 multTumRptAsOnePrim $1 dateOfMultTumors $1 multiplicityCounter $1 ;
    length gradePathSystem $1 siteCodingSysCurrent $1 siteCodingSysOriginal $1 morphCodingSysCurrent $1 morphCodingSysOriginl $1 diagnosticConfirmation $1 ;
    length typeOfReportingSource $1 casefindingSource $1 histologicTypeIcdO3 $1 behaviorCodeIcdO3 $1 sequenceNumberHospital $1 abstractedBy $1 ;
    length dateOf1stContact $1 dateOfInptAdm $1 dateOfInptDisch $1 classOfCase $1 primaryPayerAtDx $1 rxHospSurgApp2010 $1 ;
    length rxHospSurgPrimSite $1 rxHospScopeRegLnSur $1 rxHospSurgOthRegDis $1 rxHospRegLnRemoved $1 dateRegionalLNDissection $1 rxHospRadiation $1 ;
    length rxHospChemo $1 rxHospHormone $1 rxHospBrm $1 rxHospOther $1 rxHospDxStgProc $1 rxHospSurgSite9802 $1 ;
    length rxHospScopeReg9802 $1 rxHospSurgOth9802 $1 tumorSizeClinical $1 tumorSizePathologic $1 tumorSizeSummary $1 seerSummaryStage2000 $1 ;
    length seerSummaryStage1977 $1 derivedSummaryStage2018 $1 summaryStage2018 $1 eodPrimaryTumor $1 eodRegionalNodes $1 eodMets $1 ;
    length eodTumorSize $1 derivedEod2018T $1 eodExtension $1 derivedEod2018M $1 eodExtensionProstPath $1 eodLymphNodeInvolv $1 ;
    length derivedEod2018N $1 derivedEod2018StageGroup $1 regionalNodesPositive $1 regionalNodesExamined $1 dateSentinelLymphNodeBiopsy $1 sentinelLymphNodesExamined $1 ;
    length sentinelLymphNodesPositive $1 eodOld13Digit $1 eodOld2Digit $1 eodOld4Digit $1 codingSystemForEod $1 tnmPathT $1 ;
    length tnmPathN $1 tnmPathM $1 tnmPathStageGroup $1 tnmPathDescriptor $1 tnmPathStagedBy $1 tnmClinT $1 ;
    length tnmClinN $1 tnmClinM $1 tnmClinStageGroup $1 tnmClinDescriptor $1 tnmClinStagedBy $1 ajccId $1 ;
    length ajccTnmClinT $1 ajccTnmClinN $1 ajccTnmClinM $1 ajccTnmClinStageGroup $1 ajccTnmPathT $1 ajccTnmPathN $1 ;
    length ajccTnmPathM $1 ajccTnmPathStageGroup $1 ajccTnmPostTherapyT $1 ajccTnmPostTherapyN $1 ajccTnmPostTherapyM $1 ajccTnmPostTherapyStageGroup $1 ;
    length ajccTnmClinTSuffix $1 ajccTnmPathTSuffix $1 ajccTnmPostTherapyTSuffix $1 ajccTnmClinNSuffix $1 ajccTnmPathNSuffix $1 ajccTnmPostTherapyNSuffix $1 ;
    length tnmEditionNumber $1 metsAtDxBone $1 metsAtDxBrain $1 metsAtDxDistantLn $1 metsAtDxLiver $1 metsAtDxLung $1 ;
    length metsAtDxOther $1 pediatricStage $1 pediatricStagingSystem $1 pediatricStagedBy $1 tumorMarker1 $1 tumorMarker2 $1 ;
    length tumorMarker3 $1 lymphVascularInvasion $1 rxDateSurgery $1 rxDateRadiation $1 rxDateChemo $1 rxDateHormone $1 ;
    length rxDateBrm $1 rxDateOther $1 dateInitialRxSeer $1 date1stCrsRxCoc $1 rxDateDxStgProc $1 rxSummTreatmentStatus $1 ;
    length rxSummSurgPrimSite $1 rxSummScopeRegLnSur $1 rxSummSurgOthRegDis $1 rxSummRegLnExamined $1 rxSummSurgicalApproch $1 rxSummSurgicalMargins $1 ;
    length rxSummReconstruct1st $1 reasonForNoSurgery $1 rxSummDxStgProc $1 rxSummRadiation $1 rxSummRadToCns $1 rxSummSurgRadSeq $1 ;
    length rxSummChemo $1 rxSummHormone $1 rxSummBrm $1 rxSummOther $1 reasonForNoRadiation $1 rxCodingSystemCurrent $1 ;
    length phase1DosePerFraction $1 phase1RadiationExternalBeamTech $1 phase1NumberOfFractions $1 phase1RadiationPrimaryTxVolume $1 phase1RadiationToDrainingLN $1 phase1RadiationTreatmentModality $1 ;
    length phase1TotalDose $1 phase2DosePerFraction $1 phase2RadiationExternalBeamTech $1 phase2NumberOfFractions $1 phase2RadiationPrimaryTxVolume $1 phase2RadiationToDrainingLN $1 ;
    length phase2RadiationTreatmentModality $1 phase2TotalDose $1 phase3DosePerFraction $1 phase3RadiationExternalBeamTech $1 phase3NumberOfFractions $1 phase3RadiationPrimaryTxVolume $1 ;
    length phase3RadiationToDrainingLN $1 phase3RadiationTreatmentModality $1 phase3TotalDose $1 radiationTxDiscontinuedEarly $1 numberPhasesOfRadTxToVolume $1 totalDose $1 ;
    length radLocationOfRx $1 radRegionalRxModality $1 rxSummSystemicSurSeq $1 rxSummSurgeryType $1 rxSummSurgSite9802 $1 rxSummScopeReg9802 $1 ;
    length rxSummSurgOth9802 $1 subsqRx2ndCourseDate $1 subsqRx2ndCourseSurg $1 subsqRx2ndCourseRad $1 subsqRx2ndCourseChemo $1 subsqRx2ndCourseHorm $1 ;
    length subsqRx2ndCourseBrm $1 subsqRx2ndCourseOth $1 subsqRx2ndScopeLnSu $1 subsqRx2ndSurgOth $1 subsqRx2ndRegLnRem $1 subsqRx3rdCourseDate $1 ;
    length subsqRx3rdCourseSurg $1 subsqRx3rdCourseRad $1 subsqRx3rdCourseChemo $1 subsqRx3rdCourseHorm $1 subsqRx3rdCourseBrm $1 subsqRx3rdCourseOth $1 ;
    length subsqRx3rdScopeLnSu $1 subsqRx3rdSurgOth $1 subsqRx3rdRegLnRem $1 subsqRx4thCourseDate $1 subsqRx4thCourseSurg $1 subsqRx4thCourseRad $1 ;
    length subsqRx4thCourseChemo $1 subsqRx4thCourseHorm $1 subsqRx4thCourseBrm $1 subsqRx4thCourseOth $1 subsqRx4thScopeLnSu $1 subsqRx4thSurgOth $1 ;
    length subsqRx4thRegLnRem $1 dateOfLastContact $1 dateOfDeathCanada $1 vitalStatus $1 vitalStatusRecode $1 cancerStatus $1 ;
    length dateOfLastCancerStatus $1 recordNumberRecode $1 survDateActiveFollowup $1 survFlagActiveFollowup $1 survMosActiveFollowup $1 survDatePresumedAlive $1 ;
    length survFlagPresumedAlive $1 survMosPresumedAlive $1 survDateDxRecode $1 followUpSource $1 followUpSourceCentral $1 nextFollowUpSource $1 ;
    length addrCurrentState $1 addrCurrentCountry $1 followUpContactState $1 followupContactCountry $1 unusualFollowUpMethod $1 recurrenceDate1st $1 ;
    length recurrenceType1st $1 causeOfDeath $1 seerCauseSpecificCod $1 seerOtherCod $1 icdRevisionNumber $1 autopsy $1 ;
    length placeOfDeathState $1 placeOfDeathCountry $1 siteIcdO1 $1 histologyIcdO1 $1 behaviorIcdO1 $1 gradeIcdO1 $1 ;
    length overRideSsNodespos $1 overRideSsTnmN $1 overRideSsTnmM $1 overRideAcsnClassSeq $1 overRideHospseqDxconf $1 overRideCocSiteType $1 ;
    length overRideHospseqSite $1 overRideSiteTnmStggrp $1 overRideAgeSiteMorph $1 overRideTnmStage $1 overRideTnmTis $1 overRideTnm3 $1 ;
    length overRideSeqnoDxconf $1 overRideSiteLatSeqno $1 overRideSurgDxconf $1 overRideSiteType $1 overRideHistology $1 overRideReportSource $1 ;
    length overRideIllDefineSite $1 overRideLeukLymphoma $1 overRideSiteBehavior $1 overRideSiteEodDxDt $1 overRideSiteLatEod $1 overRideSiteLatMorph $1 ;
    length overRideNameSex $1 dateCaseInitiated $1 dateCaseCompleted $1 dateCaseCompletedCoc $1 dateCaseLastChanged $1 dateCaseReportExported $1 ;
    length dateCaseReportReceived $1 dateCaseReportLoaded $1 dateTumorRecordAvailbl $1 icdO3ConversionFlag $1 cocCodingSysCurrent $1 cocCodingSysOriginal $1 ;
    length cocAccreditedFlag $1 vendorName $1 csTumorSize $1 csExtension $1 csTumorSizeExtEval $1 csLymphNodes $1 ;
    length csLymphNodesEval $1 csMetsAtDx $1 csMetsAtDxBone $1 csMetsAtDxBrain $1 csMetsAtDxLiver $1 csMetsAtDxLung $1 ;
    length csMetsEval $1 csSiteSpecificFactor7 $1 csSiteSpecificFactor8 $1 csSiteSpecificFactor9 $1 csSiteSpecificFactor10 $1 csSiteSpecificFactor11 $1 ;
    length csSiteSpecificFactor12 $1 csSiteSpecificFactor13 $1 csSiteSpecificFactor14 $1 csSiteSpecificFactor15 $1 csSiteSpecificFactor16 $1 csSiteSpecificFactor17 $1 ;
    length csSiteSpecificFactor18 $1 csSiteSpecificFactor19 $1 csSiteSpecificFactor20 $1 csSiteSpecificFactor21 $1 csSiteSpecificFactor22 $1 csSiteSpecificFactor23 $1 ;
    length csSiteSpecificFactor24 $1 csSiteSpecificFactor25 $1 csSiteSpecificFactor1 $1 csSiteSpecificFactor2 $1 csSiteSpecificFactor3 $1 csSiteSpecificFactor4 $1 ;
    length csSiteSpecificFactor5 $1 csSiteSpecificFactor6 $1 csVersionInputOriginal $1 csVersionDerived $1 csVersionInputCurrent $1 derivedAjcc6T $1 ;
    length derivedAjcc6TDescript $1 derivedAjcc6N $1 derivedAjcc6NDescript $1 derivedAjcc6M $1 derivedAjcc6MDescript $1 derivedAjcc6StageGrp $1 ;
    length derivedSs1977 $1 derivedSs2000 $1 derivedAjccFlag $1 derivedSs1977Flag $1 derivedSs2000Flag $1 comorbidComplication1 $1 ;
    length comorbidComplication2 $1 comorbidComplication3 $1 comorbidComplication4 $1 comorbidComplication5 $1 comorbidComplication6 $1 comorbidComplication7 $1 ;
    length comorbidComplication8 $1 comorbidComplication9 $1 comorbidComplication10 $1 icdRevisionComorbid $1 rxDateMostDefinSurg $1 rxDateSurgicalDisch $1 ;
    length readmSameHosp30Days $1 rxDateRadiationEnded $1 rxDateSystemic $1 rxSummTransplntEndocr $1 rxSummPalliativeProc $1 rxHospPalliativeProc $1 ;
    length ruralurbanContinuum1993 $1 ruralurbanContinuum2003 $1 ruralurbanContinuum2013 $1 derivedAjcc7T $1 derivedAjcc7TDescript $1 derivedAjcc7N $1 ;
    length derivedAjcc7NDescript $1 derivedAjcc7M $1 derivedAjcc7MDescript $1 derivedAjcc7StageGrp $1 derivedSeerPathStgGrp $1 derivedSeerClinStgGrp $1 ;
    length derivedSeerCmbStgGrp $1 derivedSeerCombinedT $1 derivedSeerCombinedN $1 derivedSeerCombinedM $1 derivedSeerCmbTSrc $1 derivedSeerCmbNSrc $1 ;
    length derivedSeerCmbMSrc $1 npcrDerivedAjcc8TnmClinStgGrp $1 npcrDerivedAjcc8TnmPathStgGrp $1 npcrDerivedAjcc8TnmPostStgGrp $1 seerSiteSpecificFact1 $1 seerSiteSpecificFact2 $1 ;
    length seerSiteSpecificFact3 $1 seerSiteSpecificFact4 $1 seerSiteSpecificFact5 $1 seerSiteSpecificFact6 $1 overRideCs1 $1 overRideCs2 $1 ;
    length overRideCs3 $1 overRideCs4 $1 overRideCs5 $1 overRideCs6 $1 overRideCs7 $1 overRideCs8 $1 ;
    length overRideCs9 $1 overRideCs10 $1 overRideCs11 $1 overRideCs12 $1 overRideCs13 $1 overRideCs14 $1 ;
    length overRideCs15 $1 overRideCs16 $1 overRideCs17 $1 overRideCs18 $1 overRideCs19 $1 overRideCs20 $1 ;
    length secondaryDiagnosis1 $1 secondaryDiagnosis2 $1 secondaryDiagnosis3 $1 secondaryDiagnosis4 $1 secondaryDiagnosis5 $1 secondaryDiagnosis6 $1 ;
    length secondaryDiagnosis7 $1 secondaryDiagnosis8 $1 secondaryDiagnosis9 $1 secondaryDiagnosis10 $1 schemaId $1 chromosome1pLossHeterozygosity $1 ;
    length chromosome19qLossHeterozygosity $1 adenoidCysticBasaloidPattern $1 adenopathy $1 afpPostOrchiectomyLabValue $1 afpPostOrchiectomyRange $1 afpPreOrchiectomyLabValue $1 ;
    length afpPreOrchiectomyRange $1 afpPretreatmentInterpretation $1 afpPretreatmentLabValue $1 anemia $1 bSymptoms $1 bilirubinPretxTotalLabValue $1 ;
    length bilirubinPretxUnitOfMeasure $1 boneInvasion $1 brainMolecularMarkers $1 breslowTumorThickness $1 ca125PretreatmentInterpretation $1 ceaPretreatmentInterpretation $1 ;
    length ceaPretreatmentLabValue $1 chromosome3Status $1 chromosome8qStatus $1 circumferentialResectionMargin $1 creatininePretreatmentLabValue $1 creatininePretxUnitOfMeasure $1 ;
    length estrogenReceptorPercntPosOrRange $1 estrogenReceptorSummary $1 estrogenReceptorTotalAllredScore $1 esophagusAndEgjTumorEpicenter $1 extranodalExtensionClin $1 extranodalExtensionHeadNeckClin $1 ;
    length extranodalExtensionHeadNeckPath $1 extranodalExtensionPath $1 extravascularMatrixPatterns $1 fibrosisScore $1 figoStage $1 gestationalTrophoblasticPxIndex $1 ;
    length gleasonPatternsClinical $1 gleasonPatternsPathological $1 gleasonScoreClinical $1 gleasonScorePathological $1 gleasonTertiaryPattern $1 gradeClinical $1 ;
    length gradePathological $1 gradePostTherapy $1 hcgPostOrchiectomyLabValue $1 hcgPostOrchiectomyRange $1 hcgPreOrchiectomyLabValue $1 hcgPreOrchiectomyRange $1 ;
    length her2IhcSummary $1 her2IshDualProbeCopyNumber $1 her2IshDualProbeRatio $1 her2IshSingleProbeCopyNumber $1 her2IshSummary $1 her2OverallSummary $1 ;
    length heritableTrait $1 highRiskCytogenetics $1 highRiskHistologicFeatures $1 hivStatus $1 iNRProthrombinTime $1 ipsilateralAdrenalGlandInvolve $1 ;
    length jak2 $1 ki67 $1 invasionBeyondCapsule $1 kitGeneImmunohistochemistry $1 kras $1 ldhPostOrchiectomyRange $1 ;
    length ldhPreOrchiectomyRange $1 ldhPretreatmentLevel $1 ldhUpperLimitsOfNormal $1 lnAssessMethodFemoralInguinal $1 lnAssessMethodParaaortic $1 lnAssessMethodPelvic $1 ;
    length lnDistantAssessMethod $1 lnDistantMediastinalScalene $1 lnHeadAndNeckLevels1To3 $1 lnHeadAndNeckLevels4To5 $1 lnHeadAndNeckLevels6To7 $1 lnHeadAndNeckOther $1 ;
    length lnIsolatedTumorCells $1 lnLaterality $1 lnPositiveAxillaryLevel1To2 $1 lnSize $1 lymphocytosis $1 majorVeinInvolvement $1 ;
    length measuredBasalDiameter $1 measuredThickness $1 methylationOfO6MGMT $1 microsatelliteInstability $1 microvascularDensity $1 mitoticCountUvealMelanoma $1 ;
    length mitoticRateMelanoma $1 multigeneSignatureMethod $1 multigeneSignatureResults $1 nccnInternationalPrognosticIndex $1 numberOfCoresExamined $1 numberOfCoresPositive $1 ;
    length numberOfExaminedParaAorticNodes $1 numberOfExaminedPelvicNodes $1 numberOfPositiveParaAorticNodes $1 numberOfPositivePelvicNodes $1 oncotypeDxRecurrenceScoreDcis $1 oncotypeDxRecurrenceScoreInvasiv $1 ;
    length oncotypeDxRiskLevelDcis $1 oncotypeDxRiskLevelInvasive $1 organomegaly $1 percentNecrosisPostNeoadjuvant $1 perineuralInvasion $1 peripheralBloodInvolvement $1 ;
    length peritonealCytology $1 pleuralEffusion $1 progesteroneRecepPrcntPosOrRange $1 progesteroneRecepSummary $1 progesteroneRecepTotalAllredScor $1 primarySclerosingCholangitis $1 ;
    length profoundImmuneSuppression $1 prostatePathologicalExtension $1 psaLabValue $1 residualTumVolPostCytoreduction $1 responseToNeoadjuvantTherapy $1 sCategoryClinical $1 ;
    length sCategoryPathological $1 sarcomatoidFeatures $1 schemaDiscriminator1 $1 schemaDiscriminator2 $1 schemaDiscriminator3 $1 separateTumorNodules $1 ;
    length serumAlbuminPretreatmentLevel $1 serumBeta2MicroglobulinPretxLvl $1 ldhPretreatmentLabValue $1 thrombocytopenia $1 tumorDeposits $1 tumorGrowthPattern $1 ;
    length ulceration $1 visceralParietalPleuralInvasion $1 pathDateSpecCollect1 $1 pathDateSpecCollect2 $1 pathDateSpecCollect3 $1 pathDateSpecCollect4 $1 ;
    length pathDateSpecCollect5 $1 pathReportType1 $1 pathReportType2 $1 pathReportType3 $1 pathReportType4 $1 pathReportType5 $1 ;
    length raceCodingSysCurrent $1 raceCodingSysOriginal $1 dateOfBirthFlag $1 birthplace $1 censusOccCode19702000 $1 censusIndCode19702000 $1 ;
    length censusOccIndSys7000 $1 dateOfDiagnosisFlag $1 dateOfMultTumorsFlag $1 dateConclusiveDxFlag $1 dateOf1stContactFlag $1 dateOfInptAdmFlag $1 ;
    length dateOfInptDischFlag $1 inpatientStatus $1 dateRegionalLNDissectionFlag $1 dateSentinelLymphNodeBiopsyFlag $1 rxDateSurgeryFlag $1 rxDateRadiationFlag $1 ;
    length rxDateChemoFlag $1 rxDateHormoneFlag $1 rxDateBrmFlag $1 rxDateOtherFlag $1 dateInitialRxSeerFlag $1 date1stCrsRxCocFlag $1 ;
    length rxDateDxStgProcFlag $1 radRegionalDoseCgy $1 radNoOfTreatmentVol $1 radTreatmentVolume $1 subsqRx2ndcrsDateFlag $1 subsqRx3rdcrsDateFlag $1 ;
    length subsqRx4thcrsDateFlag $1 subsqRxReconstructDel $1 dateOfLastContactFlag $1 dateOfDeathCanadaFlag $1 dateOfLastCancerStatusFlag $1 qualityOfSurvival $1 ;
    length recurrenceDate1stFlag $1 placeOfDeath $1 icdO2ConversionFlag $1 crcChecksum $1 seerCodingSysCurrent $1 seerCodingSysOriginal $1 ;
    length rqrsNcdbSubmissionFlag $1 seerTypeOfFollowUp $1 seerRecordNumber $1 diagnosticProc7387 $1 stateRequestorItems $1 militaryRecordNoSuffix $1 ;
    length nameMaiden $1 rxDateMostDefinSurgFlag $1 rxDateSurgicalDischFlag $1 radBoostRxModality $1 radBoostDoseCgy $1 rxDateRadiationEndedFlag $1 ;
    length rxDateSystemicFlag $1 derivedPrerx7T $1 derivedPrerx7TDescrip $1 derivedPrerx7N $1 derivedPrerx7NDescrip $1 derivedPrerx7M $1 ;
    length derivedPrerx7MDescrip $1 derivedPrerx7StageGrp $1 derivedPostrx7T $1 derivedPostrx7N $1 derivedPostrx7M $1 derivedPostrx7StgeGrp $1 ;
    length derivedNeoadjuvRxFlag $1 npcrDerivedClinStgGrp $1 npcrDerivedPathStgGrp $1 npcrSpecificField $1 lnStatusFemorInguinParaaortPelv $1 ;
    /* two placeholder rows */
    do _i = 1 to 2; output; end;
    drop _i;
run;
